name: PHP Code Style Check

on:
  push:
    paths:
      - '**/*.php'
      - '.php-cs-fixer.dist.php'
      - 'composer.json'
      - '.github/workflows/php-cs-fixer.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.php'
      - '.php-cs-fixer.dist.php'
      - 'composer.json'
      - '.github/workflows/php-cs-fixer.yml'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: '8.2'
          tools: php-cs-fixer
      
      - name: Run PHP CS Fixer
        run: php-cs-fixer check --verbose --show-progress=none >> $GITHUB_STEP_SUMMARY

  php-cs-fixer2:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: PHP-CS-Fixer
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/app \
            -w /app \
            ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.5@sha256:8d36b0d9d6e5800f3889c01db6f050dc75cacd08e94f7d203908db4f8b67da2c \
            check --verbose >> $GITHUB_STEP_SUMMARY
